### PR TITLE
Added Contributing.md

### PR DESCRIPTION
**Pull request by cybrpnkkrtos**
Intro to contributing

### CODE REVIEW

**Comment by readikus** [comment]
Can you elaborate on this? Not sure it is really necessary without an actual code contribution.

**Comment by readikus** [comment]
You've got `cd sysmon` - assume that's from when you copy and pasted the same for `sysmon`.

**Comment by readikus** [comment]
Doesn't it also need a code of conduct?

**Comment by cybrpnkkrtos** [comment]
> Can you elaborate on this? Not sure it is really necessary without an actual code contribution.

I thought you meant the CONTRIBUTORS.md which is generally meant as formal intro to the method of contributing on github , but it seems i misunderstood aplogoies for it @readikus .
Are you looking for contributing.md file which includes the explanation of working of the internals and how one can specifically contribute to it ?


> You've got `cd sysmon` - assume that's from when you copy and pasted the same for `sysmon`.
I was working on something earlier this morning it is my fault to have not double checked the template and misssing that single point


> Doesn't it also need a code of conduct?
if its not sarcastic , it depends on you i would be glad to help you out needing a bit info about licenses and stuff

**Pull request closed without merging**
